name: "Terraform Plan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: "Checkout code"
        uses: actions/checkout@v2

      # Step 2: Setup Terraform
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      # Step 3: Initialize Terraform
      - name: "Terraform Init"
        run: terraform init

      # Step 4: Terraform Plan
      - name: "Terraform Plan"
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
